/**
 * 全局常量定义，避免在业务代码中散落硬编码。
 */
const path = require('path')

module.exports = {
  // ---- 服务端口 ----
  DEFAULT_PORT: 3000,

  // ---- 数据库 ----
  DB_CHARSET: 'utf8mb4',
  DB_CONNECTION_LIMIT: 10,
  DB_QUEUE_LIMIT: 0,

  // ---- 文件上传 ----
  UPLOAD_DIR: path.join(__dirname, '..', 'uploads'),
  HAZARD_UPLOAD_SUBDIR: 'hazards',
  REPORT_TEMPLATE_UPLOAD_SUBDIR: 'report-templates',
  MAX_UPLOAD_FILES: 9,
  ALLOWED_IMAGE_TYPES: /\.(jpg|jpeg|png|gif|webp|bmp)$/i,
  ALLOWED_DOC_TYPES: /\.(pdf|docx|doc)$/i,

  // ---- AI 模型 ----
  ARK_BASE_URL: 'https://ark.cn-beijing.volces.com/api/v3',
  AI_DEFAULT_MAX_TOKENS: 4096,
  AI_DEFAULT_TEMPERATURE: 0.7,
  AI_INSPECTION_TEMPERATURE: 0.4,
  AI_MAX_HISTORY_LENGTH: 20,
  AI_TIMEOUT_MS: 60000,

  // ---- 账户安全 ----
  PASSWORD_SALT_LENGTH: 16,
  PASSWORD_HASH_LENGTH: 64,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCK_DURATION_MINUTES: 30,
  JWT_ACCESS_EXPIRES_IN_DEFAULT: '8h',
  JWT_FILE_EXPIRES_IN_DEFAULT: '30m',

  // ---- 日志 ----
  LOG_QUERY_LIMIT: 500,

  // ---- 角色 ----
  ROLE_ADMIN: 'admin',
  ROLE_USER: 'user',

  // ---- 状态 ----
  STATUS_ACTIVE: 'active',
  STATUS_DISABLED: 'disabled',
  STATUS_LOCKED: 'locked',
  STATUS_DELETED: 'deleted',
  STATUS_ARCHIVED: 'archived',
  STATUS_DRAFT: 'draft',
  STATUS_COMPLETED: 'completed',

  // ---- 操作类型 ----
  ACTION_LOGIN: 'LOGIN',
  ACTION_LOGOUT: 'LOGOUT',
  ACTION_AI_INSPECTION: 'AI_INSPECTION',
  ACTION_AI_HAZARD_ANALYZE_MULTI: 'AI_HAZARD_ANALYZE_MULTI',
  ACTION_UPDATE_INSPECTION_RESULT: 'UPDATE_INSPECTION_RESULT',
  ACTION_UPDATE_ENTERPRISE: 'UPDATE_ENTERPRISE',
  ACTION_DELETE_REPORT: 'DELETE_REPORT',
  ACTION_HAZARD_IMAGE_UPLOAD: 'HAZARD_IMAGE_UPLOAD',
  ACTION_HAZARD_IMAGE_DELETE: 'HAZARD_IMAGE_DELETE',
  ACTION_HAZARD_IMAGE_LABEL: 'HAZARD_IMAGE_LABEL',
  ACTION_ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER',
  ACTION_ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
  ACTION_ADMIN_ADD_USER: 'ADMIN_ADD_USER',
  ACTION_ADMIN_UPDATE_USER_PERMISSIONS: 'ADMIN_UPDATE_USER_PERMISSIONS',
  ACTION_ADMIN_ADD_ENTERPRISE: 'ADMIN_ADD_ENTERPRISE',
  ACTION_ADMIN_UPDATE_ENTERPRISE: 'ADMIN_UPDATE_ENTERPRISE',
  ACTION_ADMIN_DELETE_ENTERPRISE: 'ADMIN_DELETE_ENTERPRISE',
  ACTION_ADMIN_ADD_DEPARTMENT: 'ADMIN_ADD_DEPARTMENT',
  ACTION_ADMIN_UPDATE_DEPARTMENT: 'ADMIN_UPDATE_DEPARTMENT',
  ACTION_ADMIN_DELETE_DEPARTMENT: 'ADMIN_DELETE_DEPARTMENT',
  ACTION_ADMIN_EXPORT_ENTERPRISES: 'ADMIN_EXPORT_ENTERPRISES',
  ACTION_ADMIN_UPDATE_ENTERPRISE_PROFILE: 'ADMIN_UPDATE_ENTERPRISE_PROFILE',
  ACTION_ADMIN_ADD_REPORT_TEMPLATE: 'ADMIN_ADD_REPORT_TEMPLATE',
  ACTION_ADMIN_UPDATE_REPORT_TEMPLATE: 'ADMIN_UPDATE_REPORT_TEMPLATE',
  ACTION_ADMIN_DELETE_REPORT_TEMPLATE: 'ADMIN_DELETE_REPORT_TEMPLATE',
  ACTION_ADMIN_SET_REPORT_TEMPLATE_DEFAULT: 'ADMIN_SET_REPORT_TEMPLATE_DEFAULT',

  // ---- 系统提示词 ----
  SYSTEM_PROMPT: '你是一个安全生产社会化服务智检系统的 AI 助手。你的任务是协助用户进行安全检查、分析图片或文档内容，并提供专业建议。',
}
