/**
 * 全局常量定义，避免在业务代码中散落硬编码。
 */
const path = require('path')

module.exports = {
  // ---- 服务端口 ----
  DEFAULT_PORT: 3000,

  // ---- 数据库 ----
  DB_CHARSET: 'utf8mb4',
  DB_CONNECTION_LIMIT: 10,
  DB_QUEUE_LIMIT: 0,

  // ---- 文件上传 ----
  UPLOAD_DIR: path.join(__dirname, '..', 'uploads'),
  HAZARD_UPLOAD_SUBDIR: 'hazards',
  KNOWLEDGE_UPLOAD_SUBDIR: 'knowledge',
  REPORT_TEMPLATE_UPLOAD_SUBDIR: 'report-templates',
  BACKUP_UPLOAD_SUBDIR: 'backups',
  MAX_UPLOAD_FILES: 9,
  MAX_DOCUMENT_UPLOAD_SIZE: 20 * 1024 * 1024,
  ALLOWED_IMAGE_TYPES: /\.(jpg|jpeg|png|gif|webp|bmp)$/i,
  ALLOWED_DOC_TYPES: /\.(pdf|docx|doc)$/i,

  // ---- AI 模型 ----
  ARK_BASE_URL: 'https://ark.cn-beijing.volces.com/api/v3',
  AI_DEFAULT_MAX_TOKENS: 4096,
  AI_DEFAULT_TEMPERATURE: 0.5,
  AI_INSPECTION_TEMPERATURE: 0.1,
  AI_MAX_HISTORY_LENGTH: 20,
  AI_TIMEOUT_MS: 60000,

  // ---- 账户安全 ----
  PASSWORD_SALT_LENGTH: 16,
  PASSWORD_HASH_LENGTH: 64,
  MAX_LOGIN_ATTEMPTS: 5,
  LOCK_DURATION_MINUTES: 30,
  JWT_ACCESS_EXPIRES_IN_DEFAULT: '8h',
  JWT_FILE_EXPIRES_IN_DEFAULT: '30m',

  // ---- 日志 ----
  LOG_QUERY_LIMIT: 500,

  // ---- 角色 ----
  ROLE_ADMIN: 'admin',
  ROLE_USER: 'user',

  // ---- 状态 ----
  STATUS_ACTIVE: 'active',
  STATUS_DISABLED: 'disabled',
  STATUS_LOCKED: 'locked',
  STATUS_DELETED: 'deleted',
  STATUS_ARCHIVED: 'archived',
  STATUS_DRAFT: 'draft',
  STATUS_COMPLETED: 'completed',

  // ---- 操作类型 ----
  ACTION_LOGIN: 'LOGIN',
  ACTION_LOGOUT: 'LOGOUT',
  ACTION_AI_INSPECTION: 'AI_INSPECTION',
  ACTION_AI_HAZARD_ANALYZE_MULTI: 'AI_HAZARD_ANALYZE_MULTI',
  ACTION_UPDATE_INSPECTION_RESULT: 'UPDATE_INSPECTION_RESULT',
  ACTION_UPDATE_ENTERPRISE: 'UPDATE_ENTERPRISE',
  ACTION_DELETE_REPORT: 'DELETE_REPORT',
  ACTION_HAZARD_IMAGE_UPLOAD: 'HAZARD_IMAGE_UPLOAD',
  ACTION_HAZARD_IMAGE_DELETE: 'HAZARD_IMAGE_DELETE',
  ACTION_HAZARD_IMAGE_LABEL: 'HAZARD_IMAGE_LABEL',
  ACTION_ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER',
  ACTION_ADMIN_DELETE_USER: 'ADMIN_DELETE_USER',
  ACTION_ADMIN_ADD_USER: 'ADMIN_ADD_USER',
  ACTION_ADMIN_UPDATE_USER_PERMISSIONS: 'ADMIN_UPDATE_USER_PERMISSIONS',
  ACTION_ADMIN_ADD_ENTERPRISE: 'ADMIN_ADD_ENTERPRISE',
  ACTION_ADMIN_UPDATE_ENTERPRISE: 'ADMIN_UPDATE_ENTERPRISE',
  ACTION_ADMIN_DELETE_ENTERPRISE: 'ADMIN_DELETE_ENTERPRISE',
  ACTION_ADMIN_ADD_DEPARTMENT: 'ADMIN_ADD_DEPARTMENT',
  ACTION_ADMIN_UPDATE_DEPARTMENT: 'ADMIN_UPDATE_DEPARTMENT',
  ACTION_ADMIN_DELETE_DEPARTMENT: 'ADMIN_DELETE_DEPARTMENT',
  ACTION_ADMIN_EXPORT_ENTERPRISES: 'ADMIN_EXPORT_ENTERPRISES',
  ACTION_ADMIN_UPDATE_ENTERPRISE_PROFILE: 'ADMIN_UPDATE_ENTERPRISE_PROFILE',
  ACTION_ADMIN_ADD_KNOWLEDGE: 'ACTION_ADMIN_ADD_KNOWLEDGE',
  ACTION_ADMIN_UPDATE_KNOWLEDGE: 'ACTION_ADMIN_UPDATE_KNOWLEDGE',
  ACTION_ADMIN_ARCHIVE_KNOWLEDGE: 'ACTION_ADMIN_ARCHIVE_KNOWLEDGE',
  ACTION_ADMIN_BATCH_ARCHIVE_KNOWLEDGE: 'ACTION_ADMIN_BATCH_ARCHIVE_KNOWLEDGE',
  ACTION_ADMIN_IMPORT_LEGAL_CLAUSES: 'ACTION_ADMIN_IMPORT_LEGAL_CLAUSES',
  ACTION_ADMIN_UPDATE_KNOWLEDGE_DRAFT: 'ACTION_ADMIN_UPDATE_KNOWLEDGE_DRAFT',
  ACTION_ADMIN_APPROVE_KNOWLEDGE_DRAFT: 'ACTION_ADMIN_APPROVE_KNOWLEDGE_DRAFT',
  ACTION_ADMIN_REJECT_KNOWLEDGE_DRAFT: 'ACTION_ADMIN_REJECT_KNOWLEDGE_DRAFT',
  ACTION_ADMIN_ADD_HAZARD_RULE: 'ACTION_ADMIN_ADD_HAZARD_RULE',
  ACTION_ADMIN_UPDATE_HAZARD_RULE: 'ACTION_ADMIN_UPDATE_HAZARD_RULE',
  ACTION_ADMIN_ARCHIVE_HAZARD_RULE: 'ACTION_ADMIN_ARCHIVE_HAZARD_RULE',
  ACTION_ADMIN_TOGGLE_HAZARD_RULE: 'ACTION_ADMIN_TOGGLE_HAZARD_RULE',
  ACTION_ADMIN_IMPORT_HAZARD_RULE_SEED: 'ACTION_ADMIN_IMPORT_HAZARD_RULE_SEED',
  ACTION_ADMIN_ADD_KNOWLEDGE_CATEGORY: 'ACTION_ADMIN_ADD_KNOWLEDGE_CATEGORY',
  ACTION_ADMIN_UPDATE_KNOWLEDGE_CATEGORY: 'ACTION_ADMIN_UPDATE_KNOWLEDGE_CATEGORY',
  ACTION_ADMIN_DELETE_KNOWLEDGE_CATEGORY: 'ACTION_ADMIN_DELETE_KNOWLEDGE_CATEGORY',
  ACTION_ADMIN_ADD_REPORT_TEMPLATE: 'ADMIN_ADD_REPORT_TEMPLATE',
  ACTION_ADMIN_UPDATE_REPORT_TEMPLATE: 'ADMIN_UPDATE_REPORT_TEMPLATE',
  ACTION_ADMIN_DELETE_REPORT_TEMPLATE: 'ADMIN_DELETE_REPORT_TEMPLATE',
  ACTION_ADMIN_SET_REPORT_TEMPLATE_DEFAULT: 'ADMIN_SET_REPORT_TEMPLATE_DEFAULT',
  ACTION_ADMIN_CREATE_BACKUP: 'ADMIN_CREATE_BACKUP',

  // ---- 系统提示词 ----
  SYSTEM_PROMPT: '你是一个安全生产社会化服务智检系统的 AI 助手。你的任务只限于安全生产检查、隐患图片分析、整改建议、法规标准解释、企业安全管理和报告生成。用户提出与安全生产业务无关的问题时，应礼貌拒绝，并引导用户回到隐患排查、法规依据或报告生成场景。涉及法规条款时必须谨慎：没有本地知识条款或无法确认具体条款时，不得编造标准编号、条款号或条文全文，应明确写“需人工复核具体条款”。',
}
